# Day 2: Pandas & NumPy Fundamentals

Welcome to Day 2 of your AI & Data Engineering training.

## What is NumPy?
NumPy is a Python library for numerical computing. It provides:
- Efficient multi-dimensional arrays (ndarrays)
- Vectorized operations (fast, element-wise operations)
- Broadcasting (operations on different-shaped arrays)
- Mathematical and statistical functions

## What is Pandas?
Pandas is a data manipulation library built on top of NumPy. It provides:
- DataFrames: 2D tabular data structures (like SQL tables)
- Series: 1D labeled arrays
- Data cleaning, transformation, and analysis tools
- Merging, grouping, and pivoting operations

## Why Pandas & NumPy for Data Engineering?
- **Data Processing**: Efficiently clean and transform data at scale
- **Analysis**: GroupBy, aggregations, and exploratory data analysis (EDA)
- **Vectorization**: Fast operations without explicit loops
- **Integration**: Work with CSV, JSON, SQL databases seamlessly
- **Foundation**: Used in ETL pipelines, machine learning preprocessing, and data science

In [ ]:
import numpy as np

## Part 1: NumPy Basics

### 1.1 Creating Arrays

In [ ]:
import numpy as np

# Create arrays from Python lists
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)
print("Shape:", arr1.shape)
print("Data type:", arr1.dtype)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:")
print(arr2)
print("Shape:", arr2.shape)

# Create arrays with functions
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
range_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)

print("\nZeros (3x3):\n", zeros)
print("\nOnes (2x4):\n", ones)
print("\nRange (0 to 10, step 2):", range_arr)
print("\nLinspace (0 to 1, 5 points):", linspace_arr)

1D array: [1 2 3 4 5]
Shape: (5,)
Data type: int64

2D array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Zeros (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Range (0 to 10, step 2): [0 2 4 6 8]

Linspace (0 to 1, 5 points): [0.   0.25 0.5  0.75 1.  ]


### 1.2 Vectorization: Operations on Arrays

In [ ]:
# Vectorized operations (no explicit loops)
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Element-wise operations
print("a + b =", a + b)
print("a * b =", a * b)
print("b / a =", b / a)
print("a ** 2 =", a ** 2)
print("np.sqrt(a) =", np.sqrt(a))

# Aggregation functions
print("\nSum:", np.sum(a))
print("Mean:", np.mean(a))
print("Std Dev:", np.std(a))
print("Max:", np.max(a))
print("Min:", np.min(a))

a + b = [11 22 33 44 55]
a * b = [ 10  40  90 160 250]
b / a = [10. 10. 10. 10. 10.]
a ** 2 = [ 1  4  9 16 25]
np.sqrt(a) = [1.         1.41421356 1.73205081 2.         2.23606798]

Sum: 15
Mean: 3.0
Std Dev: 1.4142135623730951
Max: 5
Min: 1


### 1.3 Broadcasting

In [ ]:
# Broadcasting: operate on arrays of different shapes
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar = 10
vector = np.array([1, 2, 3])

print("Original matrix:")
print(matrix)

# Scalar broadcasting
print("\nMatrix + scalar (10):")
print(matrix + scalar)

# Vector broadcasting
print("\nMatrix + vector [1, 2, 3]:")
print(matrix + vector)

# Row subtraction
print("\nSubtract column mean from each element:")
col_mean = np.mean(matrix, axis=0)
print("Column means:", col_mean)
print("Matrix - column means:")
print(matrix - col_mean)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix + scalar (10):
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Matrix + vector [1, 2, 3]:
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Subtract column mean from each element:
Column means: [4. 5. 6.]
Matrix - column means:
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


### 1.4 Advanced NumPy: Reshape, Stacking, and Vectorized Indexing

In [ ]:
# Reshape and transpose
arr = np.arange(12)
print("Original 1D array:", arr)
print("Shape:", arr.shape)

arr2d = arr.reshape((3, 4))
print("\nReshaped to 3x4:\n", arr2d)
print("Transpose:\n", arr2d.T)

# Flatten and ravel
print("\nFlattened array:", arr2d.flatten())
print("Raveled array:", arr2d.ravel())

# Concatenate and stack arrays
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])
print("\nConcatenate along axis 0:", np.concatenate([c, d]))
print("Stack vertically:\n", np.vstack([c, d]))
print("Stack horizontally:\n", np.hstack([c, d]))

# Boolean masking and fancy indexing
vector = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
mask = vector > 50
print("\nOriginal vector:\n", vector)
print("Mask (vector > 50):\n", mask)
print("Values greater than 50:", vector[mask])

# Vectorized conditional selection
thresholded = np.where(vector % 2 == 0, vector, -1)
print("\nReplace odd values with -1:\n", thresholded)

# Einstein summation for matrix multiplication
x = np.arange(1, 7).reshape(2, 3)
y = np.arange(7, 13).reshape(3, 2)
print("\nMatrix multiplication with einsum:\n", np.einsum('ij,jk->ik', x, y))

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Concatenate along axis 0: [1 2 3 4 5 6]
Stack vertically:
 [[1 2 3]
 [4 5 6]]
Stack horizontally:
 [1 2 3 4 5 6]

Original vector:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Mask (vector > 50):
 [[False False False]
 [False False  True]
 [ True  True  True]]
Values greater than 50: [60 70 80 90]

Replace odd values with -1:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Matrix multiplication with einsum:
 [[ 58  64]
 [139 154]]


## Part 2: Pandas DataFrames

### 2.1 Creating and Exploring DataFrames

In [ ]:
import pandas as pd

# Create a DataFrame from a dictionary
data = {
    'patient_id': [101, 102, 103, 104, 105],
    'age': [45, 32, 58, 41, 37],
    'condition': ['Diabetes', 'Hypertension', 'Asthma', 'Diabetes', 'Normal'],
    'visits': [5, 3, 8, 6, 1],
    'cost': [1200, 800, 950, 1100, 200]
}

df = pd.DataFrame(data)
print("DataFrame:")
print(df)

# Basic info
print("\nDataFrame info:")
print(df.info())

# Summary statistics
print("\nSummary statistics:")
print(df.describe())

### 2.2 Selecting and Filtering Data

In [ ]:
# Select single column (returns Series)
ages = df['age']
print("Ages column:")
print(ages)
print("Type:", type(ages))

# Select multiple columns (returns DataFrame)
subset = df[['patient_id', 'age', 'visits']]
print("\nMultiple columns:")
print(subset)

# Filter rows by condition
high_cost = df[df['cost'] > 1000]
print("\nPatients with cost > 1000:")
print(high_cost)

# Multiple conditions
filtered = df[(df['age'] > 40) & (df['visits'] > 3)]
print("\nPatients with age > 40 AND visits > 3:")
print(filtered)

### 2.2.1 Advanced Pandas: Computed Columns, Categorical Types, and Group Transforms

In [ ]:
# Add a computed column with vectorized operations
df = df.assign(cost_per_visit=lambda x: x['cost'] / x['visits'])
print("\nDataFrame with cost_per_visit column:")
print(df)

# Use loc to update rows conditionally
high_cost_rows = df['cost'] > 1000
df.loc[high_cost_rows, 'priority'] = 'High'
df.loc[~high_cost_rows, 'priority'] = 'Normal'
print("\nPriority labels based on cost:")
print(df[['patient_id', 'cost', 'priority']])

# Convert a datetime-like column and extract the month name
appointments = pd.DataFrame({
    'patient_id': [101, 102, 103, 104, 105],
    'appointment_date': ['2024-01-10', '2024-01-15', '2024-02-01', '2024-02-10', '2024-03-05']
})
appointments['appointment_date'] = pd.to_datetime(appointments['appointment_date'])
appointments['month'] = appointments['appointment_date'].dt.month_name()
print("\nAppointment month extraction:")
print(appointments)

# Create an ordered categorical type for conditions
condition_order = pd.CategoricalDtype(['Normal', 'Asthma', 'Hypertension', 'Diabetes'], ordered=True)
df['condition'] = df['condition'].astype(condition_order)
print("\nCondition categories and type:")
print(df.dtypes[['condition']])

# Add group-level mean cost back to each row using transform
mean_cost_by_condition = df.groupby('condition')['cost'].transform('mean')
df['condition_avg_cost'] = mean_cost_by_condition
print("\nDataFrame with condition average cost column:")
print(df[['patient_id', 'condition', 'cost', 'condition_avg_cost']])

### 2.3 GroupBy and Aggregation

In [ ]:
# GroupBy with single aggregation
print("Average cost per condition:")
print(df.groupby('condition')['cost'].mean())

# Multiple aggregations
print("\nGrouped statistics:")
grouped = df.groupby('condition').agg({
    'patient_id': 'count',
    'cost': ['sum', 'mean', 'max'],
    'visits': 'mean'
})
print(grouped)

# Custom aggregation with named columns
print("\nCustom groupby summary:")
summary = df.groupby('condition').agg(
    patient_count=('patient_id', 'count'),
    total_cost=('cost', 'sum'),
    avg_cost=('cost', 'mean'),
    avg_visits=('visits', 'mean')
)
print(summary)

### 2.4 Pivot Tables

In [ ]:
# Create larger dataset for pivot example
pivot_data = {
    'patient_id': [101, 102, 103, 101, 102, 103, 101, 102, 103],
    'month': ['Jan', 'Jan', 'Jan', 'Feb', 'Feb', 'Feb', 'Mar', 'Mar', 'Mar'],
    'condition': ['Diabetes', 'Hypertension', 'Asthma', 'Diabetes', 'Hypertension', 'Asthma', 'Diabetes', 'Hypertension', 'Asthma'],
    'visits': [2, 1, 3, 1, 2, 2, 3, 1, 4],
    'cost': [400, 300, 500, 300, 400, 450, 500, 300, 600]
}

df_pivot = pd.DataFrame(pivot_data)

# Pivot table: condition vs month, values = visits
print("Visits by condition and month:")
pivot = df_pivot.pivot_table(index='condition', columns='month', values='visits', aggfunc='sum')
print(pivot)

# Pivot with multiple aggregations
print("\nCost statistics by condition:")
pivot_cost = df_pivot.pivot_table(index='condition', values='cost', aggfunc=['sum', 'mean', 'count'])
print(pivot_cost)

### 2.5 Merging DataFrames

In [ ]:
# Create two DataFrames to merge
patients = pd.DataFrame({
    'patient_id': [101, 102, 103],
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [45, 32, 58]
})

visits = pd.DataFrame({
    'patient_id': [101, 102, 103, 101],
    'visit_date': ['2024-01-10', '2024-01-15', '2024-01-20', '2024-02-05'],
    'cost': [150, 200, 180, 150]
})

print("Patients:")
print(patients)
print("\nVisits:")
print(visits)

# Inner merge (only matching records)
print("\nInner merge:")
merged = pd.merge(patients, visits, on='patient_id', how='inner')
print(merged)

# Left merge (all from left, matching from right)
print("\nLeft merge:")
merged_left = pd.merge(patients, visits, on='patient_id', how='left')
print(merged_left)

## Key Takeaways

1. **NumPy Arrays**: Fast, efficient arrays for numerical computing
2. **Vectorization**: Perform operations without explicit loops
3. **Broadcasting**: Operate on arrays of different shapes seamlessly
4. **Pandas DataFrames**: Tabular data structures for analysis
5. **GroupBy**: Aggregate data by groups
6. **Pivot Tables**: Reorganize data for analysis
7. **Merging**: Combine data from multiple sources

## Practice Exercise

1. Create a NumPy array with numbers 1 to 10.
2. Calculate the mean and standard deviation using NumPy.
3. Create a DataFrame with sample patient data.
4. Group by condition and calculate average cost.
5. Create a pivot table showing visits by month and condition.